import com.minek.kotlin.everywehre.keuson.convert.Converter
import com.minek.kotlin.everywehre.keuson.convert.Converters
import com.minek.kotlin.everywehre.keuson.decode.Decoders
import com.minek.kotlin.everywehre.keuson.decode.map
import com.minek.kotlin.everywehre.keuson.encode.Encoder
import com.minek.kotlin.everywehre.keuson.encode.Encoders

fun <T1, U> Converters.object1(mapper: (T1) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, U> Converters.object2(mapper: (T1, T2) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, U> Converters.object3(mapper: (T1, T2, T3) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, U> Converters.object4(mapper: (T1, T2, T3, T4) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, U> Converters.object5(mapper: (T1, T2, T3, T4, T5) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, U> Converters.object6(mapper: (T1, T2, T3, T4, T5, T6) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, U> Converters.object7(mapper: (T1, T2, T3, T4, T5, T6, T7) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, U> Converters.object8(mapper: (T1, T2, T3, T4, T5, T6, T7, T8) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, U> Converters.object9(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, U> Converters.object10(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, U> Converters.object11(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, U> Converters.object12(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, U> Converters.object13(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>, t13: Pair<Pair<String, (U) -> T13>, Converter<T13>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)), t13.first.first to t13.second.first(t13.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), Decoders.field(t13.first.first, t13.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, U> Converters.object14(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>, t13: Pair<Pair<String, (U) -> T13>, Converter<T13>>, t14: Pair<Pair<String, (U) -> T14>, Converter<T14>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)), t13.first.first to t13.second.first(t13.first.second(it)), t14.first.first to t14.second.first(t14.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), Decoders.field(t13.first.first, t13.second.second), Decoders.field(t14.first.first, t14.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, U> Converters.object15(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>, t13: Pair<Pair<String, (U) -> T13>, Converter<T13>>, t14: Pair<Pair<String, (U) -> T14>, Converter<T14>>, t15: Pair<Pair<String, (U) -> T15>, Converter<T15>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)), t13.first.first to t13.second.first(t13.first.second(it)), t14.first.first to t14.second.first(t14.first.second(it)), t15.first.first to t15.second.first(t15.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), Decoders.field(t13.first.first, t13.second.second), Decoders.field(t14.first.first, t14.second.second), Decoders.field(t15.first.first, t15.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, U> Converters.object16(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>, t13: Pair<Pair<String, (U) -> T13>, Converter<T13>>, t14: Pair<Pair<String, (U) -> T14>, Converter<T14>>, t15: Pair<Pair<String, (U) -> T15>, Converter<T15>>, t16: Pair<Pair<String, (U) -> T16>, Converter<T16>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)), t13.first.first to t13.second.first(t13.first.second(it)), t14.first.first to t14.second.first(t14.first.second(it)), t15.first.first to t15.second.first(t15.first.second(it)), t16.first.first to t16.second.first(t16.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), Decoders.field(t13.first.first, t13.second.second), Decoders.field(t14.first.first, t14.second.second), Decoders.field(t15.first.first, t15.second.second), Decoders.field(t16.first.first, t16.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, U> Converters.object17(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>, t13: Pair<Pair<String, (U) -> T13>, Converter<T13>>, t14: Pair<Pair<String, (U) -> T14>, Converter<T14>>, t15: Pair<Pair<String, (U) -> T15>, Converter<T15>>, t16: Pair<Pair<String, (U) -> T16>, Converter<T16>>, t17: Pair<Pair<String, (U) -> T17>, Converter<T17>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)), t13.first.first to t13.second.first(t13.first.second(it)), t14.first.first to t14.second.first(t14.first.second(it)), t15.first.first to t15.second.first(t15.first.second(it)), t16.first.first to t16.second.first(t16.first.second(it)), t17.first.first to t17.second.first(t17.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), Decoders.field(t13.first.first, t13.second.second), Decoders.field(t14.first.first, t14.second.second), Decoders.field(t15.first.first, t15.second.second), Decoders.field(t16.first.first, t16.second.second), Decoders.field(t17.first.first, t17.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, U> Converters.object18(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>, t13: Pair<Pair<String, (U) -> T13>, Converter<T13>>, t14: Pair<Pair<String, (U) -> T14>, Converter<T14>>, t15: Pair<Pair<String, (U) -> T15>, Converter<T15>>, t16: Pair<Pair<String, (U) -> T16>, Converter<T16>>, t17: Pair<Pair<String, (U) -> T17>, Converter<T17>>, t18: Pair<Pair<String, (U) -> T18>, Converter<T18>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)), t13.first.first to t13.second.first(t13.first.second(it)), t14.first.first to t14.second.first(t14.first.second(it)), t15.first.first to t15.second.first(t15.first.second(it)), t16.first.first to t16.second.first(t16.first.second(it)), t17.first.first to t17.second.first(t17.first.second(it)), t18.first.first to t18.second.first(t18.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), Decoders.field(t13.first.first, t13.second.second), Decoders.field(t14.first.first, t14.second.second), Decoders.field(t15.first.first, t15.second.second), Decoders.field(t16.first.first, t16.second.second), Decoders.field(t17.first.first, t17.second.second), Decoders.field(t18.first.first, t18.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, U> Converters.object19(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>, t13: Pair<Pair<String, (U) -> T13>, Converter<T13>>, t14: Pair<Pair<String, (U) -> T14>, Converter<T14>>, t15: Pair<Pair<String, (U) -> T15>, Converter<T15>>, t16: Pair<Pair<String, (U) -> T16>, Converter<T16>>, t17: Pair<Pair<String, (U) -> T17>, Converter<T17>>, t18: Pair<Pair<String, (U) -> T18>, Converter<T18>>, t19: Pair<Pair<String, (U) -> T19>, Converter<T19>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)), t13.first.first to t13.second.first(t13.first.second(it)), t14.first.first to t14.second.first(t14.first.second(it)), t15.first.first to t15.second.first(t15.first.second(it)), t16.first.first to t16.second.first(t16.first.second(it)), t17.first.first to t17.second.first(t17.first.second(it)), t18.first.first to t18.second.first(t18.first.second(it)), t19.first.first to t19.second.first(t19.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), Decoders.field(t13.first.first, t13.second.second), Decoders.field(t14.first.first, t14.second.second), Decoders.field(t15.first.first, t15.second.second), Decoders.field(t16.first.first, t16.second.second), Decoders.field(t17.first.first, t17.second.second), Decoders.field(t18.first.first, t18.second.second), Decoders.field(t19.first.first, t19.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, U> Converters.object20(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>, t13: Pair<Pair<String, (U) -> T13>, Converter<T13>>, t14: Pair<Pair<String, (U) -> T14>, Converter<T14>>, t15: Pair<Pair<String, (U) -> T15>, Converter<T15>>, t16: Pair<Pair<String, (U) -> T16>, Converter<T16>>, t17: Pair<Pair<String, (U) -> T17>, Converter<T17>>, t18: Pair<Pair<String, (U) -> T18>, Converter<T18>>, t19: Pair<Pair<String, (U) -> T19>, Converter<T19>>, t20: Pair<Pair<String, (U) -> T20>, Converter<T20>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)), t13.first.first to t13.second.first(t13.first.second(it)), t14.first.first to t14.second.first(t14.first.second(it)), t15.first.first to t15.second.first(t15.first.second(it)), t16.first.first to t16.second.first(t16.first.second(it)), t17.first.first to t17.second.first(t17.first.second(it)), t18.first.first to t18.second.first(t18.first.second(it)), t19.first.first to t19.second.first(t19.first.second(it)), t20.first.first to t20.second.first(t20.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), Decoders.field(t13.first.first, t13.second.second), Decoders.field(t14.first.first, t14.second.second), Decoders.field(t15.first.first, t15.second.second), Decoders.field(t16.first.first, t16.second.second), Decoders.field(t17.first.first, t17.second.second), Decoders.field(t18.first.first, t18.second.second), Decoders.field(t19.first.first, t19.second.second), Decoders.field(t20.first.first, t20.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, U> Converters.object21(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>, t13: Pair<Pair<String, (U) -> T13>, Converter<T13>>, t14: Pair<Pair<String, (U) -> T14>, Converter<T14>>, t15: Pair<Pair<String, (U) -> T15>, Converter<T15>>, t16: Pair<Pair<String, (U) -> T16>, Converter<T16>>, t17: Pair<Pair<String, (U) -> T17>, Converter<T17>>, t18: Pair<Pair<String, (U) -> T18>, Converter<T18>>, t19: Pair<Pair<String, (U) -> T19>, Converter<T19>>, t20: Pair<Pair<String, (U) -> T20>, Converter<T20>>, t21: Pair<Pair<String, (U) -> T21>, Converter<T21>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)), t13.first.first to t13.second.first(t13.first.second(it)), t14.first.first to t14.second.first(t14.first.second(it)), t15.first.first to t15.second.first(t15.first.second(it)), t16.first.first to t16.second.first(t16.first.second(it)), t17.first.first to t17.second.first(t17.first.second(it)), t18.first.first to t18.second.first(t18.first.second(it)), t19.first.first to t19.second.first(t19.first.second(it)), t20.first.first to t20.second.first(t20.first.second(it)), t21.first.first to t21.second.first(t21.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), Decoders.field(t13.first.first, t13.second.second), Decoders.field(t14.first.first, t14.second.second), Decoders.field(t15.first.first, t15.second.second), Decoders.field(t16.first.first, t16.second.second), Decoders.field(t17.first.first, t17.second.second), Decoders.field(t18.first.first, t18.second.second), Decoders.field(t19.first.first, t19.second.second), Decoders.field(t20.first.first, t20.second.second), Decoders.field(t21.first.first, t21.second.second), mapper)
    return encoder to decoder
}

fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, U> Converters.object22(mapper: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22) -> U, t1: Pair<Pair<String, (U) -> T1>, Converter<T1>>, t2: Pair<Pair<String, (U) -> T2>, Converter<T2>>, t3: Pair<Pair<String, (U) -> T3>, Converter<T3>>, t4: Pair<Pair<String, (U) -> T4>, Converter<T4>>, t5: Pair<Pair<String, (U) -> T5>, Converter<T5>>, t6: Pair<Pair<String, (U) -> T6>, Converter<T6>>, t7: Pair<Pair<String, (U) -> T7>, Converter<T7>>, t8: Pair<Pair<String, (U) -> T8>, Converter<T8>>, t9: Pair<Pair<String, (U) -> T9>, Converter<T9>>, t10: Pair<Pair<String, (U) -> T10>, Converter<T10>>, t11: Pair<Pair<String, (U) -> T11>, Converter<T11>>, t12: Pair<Pair<String, (U) -> T12>, Converter<T12>>, t13: Pair<Pair<String, (U) -> T13>, Converter<T13>>, t14: Pair<Pair<String, (U) -> T14>, Converter<T14>>, t15: Pair<Pair<String, (U) -> T15>, Converter<T15>>, t16: Pair<Pair<String, (U) -> T16>, Converter<T16>>, t17: Pair<Pair<String, (U) -> T17>, Converter<T17>>, t18: Pair<Pair<String, (U) -> T18>, Converter<T18>>, t19: Pair<Pair<String, (U) -> T19>, Converter<T19>>, t20: Pair<Pair<String, (U) -> T20>, Converter<T20>>, t21: Pair<Pair<String, (U) -> T21>, Converter<T21>>, t22: Pair<Pair<String, (U) -> T22>, Converter<T22>>): Converter<U> {
    val encoder: Encoder<U> = {
        Encoders.object_(t1.first.first to t1.second.first(t1.first.second(it)), t2.first.first to t2.second.first(t2.first.second(it)), t3.first.first to t3.second.first(t3.first.second(it)), t4.first.first to t4.second.first(t4.first.second(it)), t5.first.first to t5.second.first(t5.first.second(it)), t6.first.first to t6.second.first(t6.first.second(it)), t7.first.first to t7.second.first(t7.first.second(it)), t8.first.first to t8.second.first(t8.first.second(it)), t9.first.first to t9.second.first(t9.first.second(it)), t10.first.first to t10.second.first(t10.first.second(it)), t11.first.first to t11.second.first(t11.first.second(it)), t12.first.first to t12.second.first(t12.first.second(it)), t13.first.first to t13.second.first(t13.first.second(it)), t14.first.first to t14.second.first(t14.first.second(it)), t15.first.first to t15.second.first(t15.first.second(it)), t16.first.first to t16.second.first(t16.first.second(it)), t17.first.first to t17.second.first(t17.first.second(it)), t18.first.first to t18.second.first(t18.first.second(it)), t19.first.first to t19.second.first(t19.first.second(it)), t20.first.first to t20.second.first(t20.first.second(it)), t21.first.first to t21.second.first(t21.first.second(it)), t22.first.first to t22.second.first(t22.first.second(it)))
    }
    val decoder = map(Decoders.field(t1.first.first, t1.second.second), Decoders.field(t2.first.first, t2.second.second), Decoders.field(t3.first.first, t3.second.second), Decoders.field(t4.first.first, t4.second.second), Decoders.field(t5.first.first, t5.second.second), Decoders.field(t6.first.first, t6.second.second), Decoders.field(t7.first.first, t7.second.second), Decoders.field(t8.first.first, t8.second.second), Decoders.field(t9.first.first, t9.second.second), Decoders.field(t10.first.first, t10.second.second), Decoders.field(t11.first.first, t11.second.second), Decoders.field(t12.first.first, t12.second.second), Decoders.field(t13.first.first, t13.second.second), Decoders.field(t14.first.first, t14.second.second), Decoders.field(t15.first.first, t15.second.second), Decoders.field(t16.first.first, t16.second.second), Decoders.field(t17.first.first, t17.second.second), Decoders.field(t18.first.first, t18.second.second), Decoders.field(t19.first.first, t19.second.second), Decoders.field(t20.first.first, t20.second.second), Decoders.field(t21.first.first, t21.second.second), Decoders.field(t22.first.first, t22.second.second), mapper)
    return encoder to decoder
}
    